# Generated by Django 4.2 on 2023-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_vacancy_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company", name="city", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="vacancy", name="salary", field=models.FloatField(default=0),
        ),
    ]
